export interface PresetConfig {
  reverb: number;      // 0-100
  delay: number;       // 0-100
  chorus: number;      // 0-100
  autotune: number;    // 0-100
  autotuneKey: string;
  harmony: number;     // 0-100
  compression: number; // 0-100
}

export const presetConfigs: Record<string, PresetConfig> = {
  'simon-le-bon': {
    reverb: 35,
    delay: 50,
    chorus: 40,
    autotune: 30,
    autotuneKey: 'D',
    harmony: 25,
    compression: 70,
  },
  'dave-gahan': {
    reverb: 55,
    delay: 65,
    chorus: 35,
    autotune: 20,
    autotuneKey: 'A',
    harmony: 20,
    compression: 65,
  },
  'chris-martin': {
    reverb: 50,
    delay: 40,
    chorus: 30,
    autotune: 25,
    autotuneKey: 'G',
    harmony: 35,
    compression: 75,
  },
  'mark-hollis': {
    reverb: 25,
    delay: 20,
    chorus: 15,
    autotune: 5,
    autotuneKey: 'C',
    harmony: 0,
    compression: 40,
  },
  'bernard-sumner': {
    reverb: 35,
    delay: 55,
    chorus: 40,
    autotune: 35,
    autotuneKey: 'E',
    harmony: 30,
    compression: 60,
  },
  'morten-harket': {
    reverb: 45,
    delay: 50,
    chorus: 45,
    autotune: 40,
    autotuneKey: 'A',
    harmony: 40,
    compression: 65,
  },
  'seal': {
    reverb: 35,
    delay: 30,
    chorus: 25,
    autotune: 15,
    autotuneKey: 'F',
    harmony: 15,
    compression: 70,
  },
  'freddie-mercury': {
    reverb: 50,
    delay: 40,
    chorus: 35,
    autotune: 10,
    autotuneKey: 'C',
    harmony: 45,
    compression: 80,
  },
  'adele': {
    reverb: 30,
    delay: 25,
    chorus: 20,
    autotune: 12,
    autotuneKey: 'D',
    harmony: 10,
    compression: 75,
  },
  'frank-sinatra': {
    reverb: 20,
    delay: 15,
    chorus: 10,
    autotune: 5,
    autotuneKey: 'C',
    harmony: 0,
    compression: 55,
  },
  'beyonce': {
    reverb: 35,
    delay: 45,
    chorus: 35,
    autotune: 45,
    autotuneKey: 'G',
    harmony: 50,
    compression: 80,
  },
  'ed-sheeran': {
    reverb: 15,
    delay: 35,
    chorus: 30,
    autotune: 20,
    autotuneKey: 'G',
    harmony: 25,
    compression: 60,
  },
  'billie-eilish': {
    reverb: 25,
    delay: 35,
    chorus: 50,
    autotune: 60,
    autotuneKey: 'A',
    harmony: 20,
    compression: 50,
  },
  'bruno-mars': {
    reverb: 20,
    delay: 25,
    chorus: 25,
    autotune: 35,
    autotuneKey: 'F',
    harmony: 30,
    compression: 85,
  },
  'ariana-grande': {
    reverb: 40,
    delay: 35,
    chorus: 40,
    autotune: 50,
    autotuneKey: 'E',
    harmony: 45,
    compression: 70,
  },
};
